name: Trading Simulator MCP CI/CD

on:
  push:
    branches: ['*']
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build project
        run: npm run build

  mcp-evaluations:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci || npm install
          npm install -D tsx
          npx tsx --version

      - name: Build project
        run: npm run build

      - name: Setup environment for evaluations
        id: setup-env
        run: |
          # Always create a .env file for consistency between local and GitHub environments
          echo "Creating .env file with secrets"
          
          # Write env file line by line
          echo "# OpenAI API key for evaluations" > .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
          echo "" >> .env
          echo "# Trading Simulator API credentials" >> .env
          echo "TRADING_SIM_API_URL=${{ secrets.TRADING_SIM_API_URL }}" >> .env
          echo "TRADING_SIM_API_KEY=${{ secrets.TRADING_SIM_API_KEY }}" >> .env
          echo "" >> .env
          echo "# Debug mode (true/false)" >> .env
          if [ -n "$ACT" ]; then
            echo "DEBUG=true" >> .env
            echo "Created .env file for local execution with act"
          else
            echo "DEBUG=${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }}" >> .env
            echo "Created .env file for GitHub Actions"
          fi
          
          # For debugging (mask the secrets)
          echo "Environment ready with:"
          echo "OPENAI_API_KEY: ${OPENAI_API_KEY:0:4}...${OPENAI_API_KEY: -4}"
          echo "TRADING_SIM_API_URL is set: $([ -n "$TRADING_SIM_API_URL" ] && echo "Yes" || echo "No")"
          echo "TRADING_SIM_API_KEY is set: $([ -n "$TRADING_SIM_API_KEY" ] && echo "Yes" || echo "No")"

      - name: Run MCP Evaluations
        run: npx tsx src/evals/evals-direct.mjs
        env:
          # These env vars are also set explicitly to ensure they're available 
          # in the current process, in addition to the .env file
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          TRADING_SIM_API_KEY: ${{ secrets.TRADING_SIM_API_KEY }}
          TRADING_SIM_API_URL: ${{ secrets.TRADING_SIM_API_URL }}
          DEBUG: ${{ github.event_name == 'workflow_dispatch' && 'true' || 'false' }} 